language: pyhton

python:
  - 3.6
evn:
  - DJANGO=1.10
install:
  - pip install pycodestyle --user
  - pip install requests[security]
  - pip install django==1.11 --quiet --user
scripts:
  - pyhton manage.py test
